drop table if exists station ;
drop table if exists ticket ;
drop table if exists vagon;
drop table if exists train;
drop table if exists route;
drop table if exists user_db ;

create table user_db(
    user_login varchar(30) PRIMARY KEY,
    user_password varchar(255) NOT NULL,
    first_name varchar(50) NOT NULL,
    second_name varchar(50) NOT NULL,
    gender varchar(50) NOT NULL,
    age INT NOT NULL,
    is_admin BOOLEAN DEFAULT FALSE
                );


create table route(
    route_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    route_name varchar(30) NOT NULL
);

create table train
(
    train_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    train_type varchar(50)  NOT NULL,
    train_name varchar(30) NOT NULL,
    route_id INT NOT NULL,
    FOREIGN KEY (route_id) REFERENCES route(route_id)
);


create table vagon
(
    vagon_number INT NOT NULL,
    vagon_number_of_seats INT NOT NULL,
    train_id INT NOT NULL,
    FOREIGN KEY (train_id) REFERENCES train(train_id),
    PRIMARY KEY(train_id, vagon_number)
);


create table ticket(
    ticket_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    price INT NOT NULL,
    seat_number varchar(30) NOT NULL,
    train_id INT NOT NULL,
    ticket_date timestamp NOT NULL,
    user_login varchar(30) NOT NULL,
    FOREIGN KEY(user_login) REFERENCES user_db(user_login),
    FOREIGN KEY(train_id) REFERENCES train(train_id)
);

create table station(
    station_number INT,
    depart_time timestamp NOT NULL,
    station_name varchar(60) NOT NULL,
    route_id INT NOT NULL,
    FOREIGN KEY(route_id) REFERENCES route(route_id),
    PRIMARY KEY(route_id, station_number)
);

INSERT INTO route(route_name) VALUES
('СПб-Мск'),
('СПб-Воронеж'),
('СПб-Омск'),
('СПб-Вологда');


INSERT INTO station(depart_time, station_number, station_name, route_id) VALUES
(timestamp '2022-12-21 00:00:00', 1, 'Санкт-Петербург', 1),
(timestamp '2022-12-21 01:03:00', 2, 'Великий Новгород', 1),
(timestamp '2022-12-21 03:55:00', 3, 'Москва', 1),

(timestamp '2022-12-21 00:00:00', 1, 'Санкт-Петербург', 2),
(timestamp '2022-12-22 01:03:00', 2, 'Воронеж', 2),

(timestamp '2022-12-23 00:00:00', 1, 'Санкт-Петербург', 3),
(timestamp '2022-12-23 01:03:00', 2, 'Омск', 3),

(timestamp '2022-12-23 00:00:00', 1, 'Санкт-Петербург', 4),
(timestamp '2022-12-24 01:03:00', 2, 'Вологда', 4);


INSERT INTO train(train_name, train_type,  route_id) VALUES
('Сапсан', 'Скоростной', 1),
('Сапсан-макс', 'Двухэтажный', 1),
('РТ-2322', 'Медленный', 2),
('Снегирь', 'Электричка', 3),
('Богатырь', 'Скоростной', 4);


INSERT INTO vagon(train_id, vagon_number, vagon_number_of_seats) VALUES
(1, 1, 52),
(1, 2, 52),
(2, 1, 52),
(2, 2, 52),
(2, 3, 52),
(2, 4, 52),
(3, 1, 52),
(4, 1, 52),
(5, 1, 52);



